# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-10 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_internalsearch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
