# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-06 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_internalsearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achar', models.TextField()),
                ('adatetime', models.DateTimeField()),
                ('aint', models.IntegerField()),
                ('aurl', models.URLField()),
                ('abool', models.BooleanField()),
            ],
        ),
    ]
