# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_internalsearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='content_type',
        ),
    ]
