# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("djangocms_internalsearch", "0002_queryproxy")]

    operations = [
        migrations.DeleteModel(name="QueryProxy"),
        migrations.CreateModel(
            name="InternalSearchProxy",
            fields=[],
            options={
                "verbose_name": "Internal Search",
                "verbose_name_plural": "Internal Search",
                "proxy": True,
                "indexes": [],
            },
            bases=("djangocms_internalsearch.query",),
        ),
    ]
