# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-08 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_internalsearch', '0002_allindex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllIndex',
        ),
        migrations.CreateModel(
            name='QueryProxy',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('djangocms_internalsearch.query',),
        ),
    ]
